#!/bin/bash
# This hook is run after every virtualenv is activated.
PS1="$_OLD_VIRTUAL_PS1"
_OLD_RPROMPT="$RPROMPT"
RPROMPT="%{${fg_bold[white]}%}(env: %{${fg[green]}%}`basename \"$VIRTUAL_ENV\"`%{${fg_bold[white]}%})%{${reset_color}%} $RPROMPT"

# don't get caught off-guard
proj_name=$(echo $VIRTUAL_ENV|awk -F'/' '{print $NF}')
mkdir -p $DEV/$proj_name/src
mkdir -p $DEV/$proj_name/data

# go
GOPATH=$VIRTUAL_ENV

cd () {
    if (( $# == 0 ))
    then
        if (( $# == 0 ))
        then
            builtin cd $VIRTUAL_ENV/src
        else
            builtin cd $VIRTUAL_ENV
        fi
    else
        builtin cd "$@"
    fi
}

cd
