#!/bin/bash
# This hook is run after a new virtualenv is created and before it is activated.

# create a /src folder in the virtualenv
proj_name=$(echo $VIRTUAL_ENV|awk -F'/' '{print $NF}')
mkdir -p $DEV/$proj_name/src
mkdir -p $DEV/$proj_name/data
mkdir -p $DEV/$proj_name/var/log
mkdir -p $DEV/$proj_name/var/run
